### ISSUE TITLE
Ability to add messages inside a chatroom successfully. 

### ISSUE THREAD

**Issue by KSLHacks** [MachUpskillingFY17/JabbR-Core#113]
Chat.js line 225

` var re = new RegExp("\\b@?" + chat.state.name.replace(/\./g, '\\.') + "\\b", "i");`
"chat.state.name is null."
Error is hit when you send the first message but is not seen after that. (still remains null)

**Comment by JamesEarle** [comment]
I'm going to look into this. It's happening on my branch as well and I think it's related to some of the work I've been doing.

**Comment by JamesEarle** [comment]
in original Jabbr, `chat.state.name` is set behind the scenes by SignalR. I think this is related to authentication / identity stuff, because the `Chat.js` files are the same between old and new, but in JabbR-Core we're spoofing the authentication with @adamtuliper's middleware.

By forcing it to call the method that updates the `chat.state.name = user.Name` line, as well as notifying the ui, we can have a visible name and no errors thrown when messages are sent. This is good, but it doesn't work consistently, and also notifies you that your name has been changed every time a message is sent as a result.

![Here is a screenshot](https://cloud.githubusercontent.com/assets/5976499/18933926/f20d3658-858b-11e6-8a52-89c0815d20f0.png)

**Comment by JamesEarle** [comment]
This has been resolved on branch `james/create-room`, because we are spoofing the user authentication a certain data pipeline isn't followed. Specifically, the user name change never takes place so when we try to send a message it doesn't know who to associate that with. I added `Clients.Caller.userNameChanged(user);` inside `Chat.Join(bool reconnecting)`.

This solves the issue, but opens another issue #126 when the page is refreshed.
