### ISSUE TITLE
Add EF bits from console app into Jabbr Core 

### ISSUE THREAD

**Issue by adamtuliper** [MachUpskillingFY17/JabbR-Core#26]
Integrate the code & models from the EF console app into JAbbr so we can start integrating EF/Models
This does not include getting the repository working, that is task #25
dependent on #22

**Comment by ashanhol** [comment]
Do we need someone to test this and #22 ? I'm free an able to test.

**Comment by jcocchi** [comment]
To test this:
-First we need to set up user secrets with the connection string since that is local to each machine
     -Make sure you are in the src directory
     -Run 'dotnet user-secrets set "connectionString" "Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=JabbRCoreDB;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"'
          -This connection string will eventually be replaced by an azure db connection, but for now use localdb

-Now that you have the connection string configured, create the database
     -In the package manager console run "Update-Database"

-The db should now be created and populated with the correct tables. You can test the connection by injecting a JabbrContext object into the HomeController constructor and adding test data to the db in the Index function

**Comment by ashanhol** [comment]
Test data added in the Index() function worked well and populated the database! :shipit:
