### ISSUE TITLE
Able to use chatroom with two users (two browsers)

### ISSUE THREAD

**Issue by KSLHacks** [MachUpskillingFY17/JabbR-Core#285]
Currently testing with (1) Chrome - Incognito and (2) Edge is unstable. Some functionality but very inconsistent. 

Stabilize for demo purposes.

**Comment by jcocchi** [comment]
Originally found this issue on dev (and on all branches off of dev). After both users joined a room for the first time in one run, they couldn't see each other's messages, but they could see their own. Only the user that joined the room second could see that the first user was in the room, but even the user that joined second couldn't see the first user's messages as they were coming in. If they both left the room and returned to the same room or a different room then they could see each other's messages and they could see that each other were online, but the other user's status was always offline when they saw these messages.

Tested this issue again on the justine/LogoutCommand branch and didn't have any of these issues. The users in both browsers were able to see each other's messages the first time they joined a room and the status of each user was online. This issue was presumably fixed because I added missing calls to UpdateActivity() and OnUserIntialize() in the Join() method of Chat.cs on my branch.
