### ISSUE TITLE
Looking at new bundling support in dotnet for jabbr core

### ISSUE THREAD

**Issue by gcrev93** [MachUpskillingFY17/JabbR-Core#8]
Looks like there are some new bundling available for .NET core

Checkout if this applies to CSS and JavaScript. Look at bundling our javascript files into one file and third party( jQuery and etc) into another

**Comment by JamesEarle** [comment]
Would be good to see if there is a way to bundle html partials. Currently they are `.cshtml` files which don't support bundling, but since the template architecture is likely to change (specifically to move away from jQuery templates) maybe this will be feasible. Should work fine if it's just Angular templates and `.html` file types.

**Comment by ashanhol** [comment]
Bundling and Minification are really easy to implement. Gulp concat and gulp uglify will work for both. 

https://docs.asp.net/en/latest/client-side/bundling-and-minification.html

**Comment by adamtuliper** [comment]
We don't want to bundle partials (you can't, they wouldn't be partials anymore) but we'll combine into a single static file later that can be hot cached and avoids runtime.

**Comment by JamesEarle** [comment]
@adamtuliper realized this after the fact. Check out @ashanhol latest update. pattern matching doesn't work for any of the file types we tried (.css and .js), glob patterns included.

**Comment by ashanhol** [comment]
**Issues**: Confused about which bundling is supposed to be native. I'm a little confused about .net core bundling. According to the official documentation here: https://docs.asp.net/en/latest/client-side/bundling-and-minification.html it references nuget and gulp for minifying and bundling.
When looking around more, other sources point to BundlerMinifier.core the NuGet package: https://www.nuget.org/packages/BundlerMinifier.Core/ which is by madds kristensen and not Microsoft.  The bundling commands work and gave us a bundleconfig.json file to edit, but when we tried to do the globbing as documented here: https://github.com/madskristensen/BundlerMinifier it wouldn't work. Which 

**To Replicate**: Run "*.json". VS2015 stalls because it's reading bundleconfig.json but also using it. VS tells you to read the error stack but it's stalled. 
"wwwroot/scripts/*.js" Z wanted to see if having a lowercase s for Scripts would affect anything, which froze both the console and VS. See pic. 
"wwwroot/**/*.css" This should have grabbed all the .css files in wwwroot->css but didn't work. 
![screenshot 4](https://cloud.githubusercontent.com/assets/9140651/18183144/e04007c4-7047-11e6-89fd-4e7738a17ad3.png)

**Comment by ashanhol** [comment]
**UPDATE**: I changed the output path name. While it seems that in the console you'll still get the error that says "No files matched the pattern", it actually does bundle AND minify the specified pattern of files. I tried checking both the bundled and minified files to see what got included. 

@adamtuliper Question: Right now I have it bundling all .js and .css files together that are in wwwroot. Do we want to separate out third party libraries vs. ones that we write?

**Comment by adamtuliper** [comment]
Create a folder called /wwwroot/js. In there we'll have our minified files from /scripts. We'll organize this a bit more once we start working on the files since most of this will end up under lib as it is. Note added to create this issue tomorrow under a Project Reorg issue.

**Comment by ashanhol** [comment]
This has been merged with pull request #91. Closing
